
public class exception1 {
    
    public static void main (String[]args){

    /* 


       // without try catch  concept
       int data = 40/0;
       System.out.println(data);
                      //java.lang.ArithmeticException: / by zero
 
    */

        /* 
            try{
               int data =20/0;
            }
            catch(ArithmeticException m){
                System.out.println(m);

            }
            System.out.println("silet of the code");

        */
        

        /*

         try{
        int data = 20/0;
        }
        catch(Exception e){
            System.out.println(e);
        }
        System.out.println("zero can't divided to 20");
       
        */

                          /* 
        int a = 30;
        int b = 0;

        try{
           int data = a/b;

        }
        catch(Exception d){
          
        System.out.println( a/(b+1) );
        }

                          */
                          
 }
}
